[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 45000
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Mqtt Export Service'
Timeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = './logs/mqtt-export.log'

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[ApplicationSettings]
MQTTHost            = "zaxdqdle:irRG_elje66K@tailor.cloudmqtt.com"
MQTTUser            = "letuan"
MQTTPass            = "24111998"
MQTTPort            = "14640"
Qos                 = "0"
KeepAlive           = "3600"
SkipCertVerify	    = "true"
PersistOnError	    = "false"
RequestTopic        = "Request"
ResponseTopic       = "Response"
MQTTCertData        = ""
MQTTKeyData         = ""

