[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'MqttExport Service'
Timeout = '5s'

[Logging]
EnableRemote = false
File = './logs/mqtt-Export.log'

[ApplicationSettings]
MQTTHost            = "zaxdqdle:irRG_elje66K@tailor.cloudmqtt.com"
MQTTUser            = "letuan"
MQTTPass            = "24111998"
MQTTPort            = "14640"
MQTTCert            = "./certs/user.client.crt"
MQTTKey             = "./certs/user.client.key"
Qos                 = "0"
KeepAlive           = "3600"
SkipCertVerify	    = "true"
PersistOnError	    = "false"

