[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'mqtt-export'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Mqtt Export Service'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080
  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = true

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""


[ApplicationSettings]
MQTTHost            = "zaxdqdle:irRG_elje66K@tailor.cloudmqtt.com"
MQTTUser            = "letuan"
MQTTPass            = "24111998"
MQTTPort            = "14640"
MQTTCert            = "./certs/user.client.crt"
MQTTKey             = "./certs/user.client.key"
Qos                 = "0"
KeepAlive           = "3600"
SkipCertVerify	    = "true"
PersistOnError	    = "false"

